### ISSUE TITLE
Unexpected Behavior Randomly Occuring

### ISSUE THREAD

**Issue by erfannf** [vivchar/RendererRecyclerViewAdapter#16]
The adapter sometimes makes a fatal error for ArrayList of items, with random happening, most of the time happens in onDetach. The Error is: 

```java
FATAL EXCEPTION: main
     Process: xx.xxx.xxxx PID: 4733
     java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
     at java.util.ArrayList.remove(ArrayList.java:503)
     at com.github.vivchar.rendererrecyclerviewadapter.RendererRecyclerViewAdapter$3.run(RendererRecyclerViewAdapter.java:261)}
```
Code in Brief:

```java
public void initUI(){
        mRecyclerViewAdapter = new RendererRecyclerViewAdapter();
        mRecyclerViewAdapter.registerRenderer(new LoadMoreViewBinder(R.layout.view_holder_load_more));
        mRecyclerViewAdapter.registerRenderer(createSearchResultPeopleBinder(R.layout.view_holder_search_result_people));
        mRecyclerViewAdapter.registerRenderer(createSearchResultTickerBinder(R.layout.view_holder_search_result_ticker));
        mRecyclerViewAdapter.registerRenderer(createSearchResultPostPreviewBinder(R.layout.view_holder_search_result_post_preview));
        mRecyclerViewAdapter.enableDiffUtil();
        rcExplore.setAdapter(mRecyclerViewAdapter);
        LinearLayoutManager lm = new LinearLayoutManager(getActivity());
        rcExplore.setLayoutManager(lm);
}
```

```java
            StringRequest stringRequest = new StringRequest(
                    Request.Method.GET,
                    url,
                    new Response.Listener<String>() {
                        @Override
                        public void onResponse(String response) {
                            Gson gson = new Gson();
                            ArrayList<Profile> searchResultsPeople = gson.fromJson(response, new TypeToken<List<Profile>>() {
                            }.getType());
                            mRecyclerViewAdapter.setItems(searchResultsPeople);
                        }
                    },
                    new Response.ErrorListener() {
                        @Override
                        public void onErrorResponse(VolleyError error) {
                            Log.d(Util.TAG, "Explore onErrorResponse: " + error.getMessage());
                        }
                    });
            Util.getInstance().addToRequestQueue(stringRequest);
        
```

```java
@NonNull
    private ViewBinder createSearchResultPeopleBinder(final int layout) {
        return new ViewBinder<>(
                layout, /* your item layout */
                Profile.class, /* your model class */
                (model, finder, payloads) -> finder
                        .setText(R.id.searchResultUsername, model.getU())
                        .setText(R.id.searchResultName, model.getN())
                        .setOnClickListener(R.id.searchResultContainer, new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                Intent intent = new Intent(getActivity(), ProfileViewer.class);
                                intent.putExtra("userid", model.getId());
                                intent.putExtra("username", model.getN());
                                intent.putExtra("profilepicture", model.getPp());
                                startActivity(intent);
                            }
                        })
        );
    }
```

**Comment by vivchar** [comment]
Yes, I had the same issue. It isn't problem of the library. You should not update RecyclerView or any UI elements when your view was detached or stopped.
```java
if(isResumed()) {
    mRecyclerViewAdapter.hideLoadMore(); // I don't see where you call hideLoadMore
    mRecyclerViewAdapter.setItems(searchResultsPeople);
}
```

and be sure that `setItems` called on UI Thread.

What version do you use?

**Comment by erfannf** [comment]
The DiffUtil is suspicious in my opinion. I guess when EndlessScrollListener getinfo is being called for page x and it returns zero size ArrayList response, this happens.Only a guess. I'll investigate.

**Comment by vivchar** [comment]
see `RendererRecyclerViewAdapter.java:261` in library, in my version it is the loadmore method.
you should call `hideLoadMore` before `setItems`

**Comment by erfannf** [comment]
Thank you. I'll check. I'm using version 2.5.1

**Comment by vivchar** [comment]
So did you solve your problem? I am going to close it
